# ----- Analysis Settings -----
analysis.mode=BASE_PSA
num.samples=1000
replications=10
spatial.distributions=1

# ----- Grid Parameters -----
grid.width=300
grid.height=300
vis.scale=1
timesteps=150

# ----- Parameter Ranges (PSA -> wide ranges) -----
effectAntiMet.min=0.0
effectAntiMet.max=1.0
effectProMet.min=0.0
effectProMet.max=1.0
S2.discrete=8.0,16.0,32.0
S4.discrete=4.0,8.0,16.0
conversionThreshold.min=0.0
conversionThreshold.max=1.0
effectPerTumorCell.min=0.0
effectPerTumorCell.max=1.0

# For each grid
grid.0.enable.astrocyteSwitch = true
grid.0.enable.chemotherapy = false