# ----- Analysis Settings -----
analysis.mode=DENSITY
num.samples=1
replications=50
spatial.distributions=6

# Density distribution
grid.0.astroGridDensity=0.0
grid.1.astroGridDensity=0.2
grid.2.astroGridDensity=0.4
grid.3.astroGridDensity=0.6
grid.4.astroGridDensity=0.8
grid.5.astroGridDensity=1.0

# ----- Grid Parameters -----
grid.width=300
grid.height=300
vis.scale=1
timesteps=150

# ----- Parameter Ranges (Targeted for density) -----
effectAntiMet.min=0.2
effectAntiMet.max=0.2
effectProMet.min=0.8
effectProMet.max=0.8
conversionThreshold.min=0.5
conversionThreshold.max=0.5
effectPerTumorCell.min=0.8
effectPerTumorCell.max=0.8
S2.discrete=8.0
S4.discrete=8.0

# For each grid
grid.0.enable.astrocyteSwitch = true
grid.0.enable.chemotherapy = false

grid.1.enable.astrocyteSwitch = true
grid.1.enable.chemotherapy = false

grid.2.enable.astrocyteSwitch = true
grid.2.enable.chemotherapy = false

grid.3.enable.astrocyteSwitch = true
grid.3.enable.chemotherapy = false

grid.4.enable.astrocyteSwitch = true
grid.4.enable.chemotherapy = false

grid.5.enable.astrocyteSwitch = true
grid.5.enable.chemotherapy = false