# ----- Analysis Settings -----
analysis.mode=SPATIAL
num.samples=1
replications=50

# Number of grids (spatial distributions)
spatial.distributions=6

# For each grid index, define which distribution to use:
distribution.0=uniform
distribution.1=random
distribution.2=clumped
distribution.3=inverseRadial
distribution.4=radial
distribution.5=gradient

# ----- Grid Parameters -----
grid.width=300
grid.height=300
vis.scale=1
timesteps=150

# ----- Parameter Ranges (Targeted for this scenario) -----
effectAntiMet.min=0.2
effectAntiMet.max=0.2
effectProMet.min=0.8
effectProMet.max=0.8
conversionThreshold.min=0.5
conversionThreshold.max=0.5
effectPerTumorCell.min=0.8
effectPerTumorCell.max=0.8
S2.discrete=8.0
S4.discrete=8.0

# For each grid
grid.0.enable.astrocyteSwitch = true
grid.0.enable.chemotherapy = false

grid.1.enable.astrocyteSwitch = true
grid.1.enable.chemotherapy = false

grid.2.enable.astrocyteSwitch = true
grid.2.enable.chemotherapy = false

grid.3.enable.astrocyteSwitch = true
grid.3.enable.chemotherapy = false

grid.4.enable.astrocyteSwitch = true
grid.4.enable.chemotherapy = false

grid.5.enable.astrocyteSwitch = true
grid.5.enable.chemotherapy = false
