# ----- Analysis Settings -----
analysis.mode=BASE
num.samples=1
replications=50
spatial.distributions=2

# ----- Grid Parameters -----
grid.width=300
grid.height=300
vis.scale=1
timesteps=150

# ----- Parameter Ranges (Fixed for BASE) -----
effectAntiMet.min=0.2
effectAntiMet.max=0.2
effectProMet.min=0.8
effectProMet.max=0.8
conversionThreshold.min=0.5
conversionThreshold.max=0.5
S2.discrete=8.0
S4.discrete=8.0
effectPerTumorCell.min=0.8
effectPerTumorCell.max=0.8

# For each grid
grid.0.enable.astrocyteSwitch = false
grid.0.enable.chemotherapy = false

grid.1.enable.astrocyteSwitch = true
grid.1.enable.chemotherapy = false